# Generated by Django 5.2 on 2025-04-30 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
