# Generated by Django 5.2 on 2025-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_remove_employee_emp_id_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
